version: '3.8'

services:
  # Laravel Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ones_group
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./vendor:/var/www/vendor
      - ./node_modules:/var/www/node_modules
    ports:
      - "9000:9000"
    networks:
      - laravel
    depends_on:
      - mysql
      - redis
      - mailpit

  # Nginx Web Server
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - laravel
    depends_on:
      - app

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ones_group
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel

  # Redis
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - laravel

  # Mailpit for email testing
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    networks:
      - laravel

  # Node.js for Vite
  node:
    image: node:18
    container_name: node
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: npm run dev
    networks:
      - laravel

# Define volumes for persistence
volumes:
  dbdata:

# Define networks
networks:
  laravel:
    driver: bridge
